name: Criar Pull Request
on:
  push:
    branches-ignore: main
jobs:
  action-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Verificação do código
        uses: actions/checkout@v2
  
      - name: Criar pull request auto
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: Criação automatica do pull request
