name: Criar Pull Request

on: [push]

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: checking out code
        uses: actions/checkout@v2
 
      - name: Set up Git
        run: | 
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Extraindo os arquivos de commit
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "main"
          title: "Atualizações automáticas"
          body: "Este pull request contém atualizações automáticas."
          committer: "github-actions <github-actions@github.com>"
