name: Criar Pull Request

on: [push]

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Extraindo os arquivos de commit
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Informações do autor do commit
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Create Pull Request
        uses: actions/github-script@v4
        with:
          script: |
            const { data: pullRequest } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Atualizações automáticas',
              body: 'Este pull request contém atualizações automáticas.',
              head: 'main',
              base: 'main'
            });
            console.log(`Pull request criado: ${pullRequest.html_url}`);
