name: Criar Pull Request

on:
  push:
    branches-ignore: main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
    
      - name: Criando pull request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "auto pull request"
          pr_title: "pull request para validação"
